import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

REPORT_RETENTION_HOURS = 168  # 7 days

DEFAULT_CONCURRENCY = 25
MAX_CONCURRENCY = 50
PER_HOST_CONCURRENCY = 10

CONNECT_TIMEOUT = 10
READ_TIMEOUT = 20
MAX_REDIRECTS = 10

RETRY_COUNT = 1
RETRY_BACKOFF = [1, 2]
RETRY_STATUSES = {502, 503, 504}
NO_RETRY_STATUSES = {404, 410, 401, 403}

MAX_XML_GZ_SIZE = 50 * 1024 * 1024
MAX_HTML_PARSE_SIZE = 512 * 1024

THIN_CONTENT_THRESHOLD = 100
VERY_THIN_CONTENT_THRESHOLD = 50
LONG_TITLE_THRESHOLD = 60
SHORT_TITLE_THRESHOLD = 10
LONG_META_DESC_THRESHOLD = 160

USER_AGENT = "SitemapHealthChecker/1.0 (+https://your-domain.example)"

ALLOWED_SCHEMES = {"http", "https"}
REJECTED_SCHEMES = {"javascript", "mailto", "data", "ftp", "file"}

TURSO_URL = os.environ.get("TURSO_DATABASE_URL", "")
TURSO_TOKEN = os.environ.get("TURSO_AUTH_TOKEN", "")
