import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

REPORT_RETENTION_HOURS = 168  # 7 days

DEFAULT_CONCURRENCY = 10
MAX_CONCURRENCY = 10
PER_HOST_CONCURRENCY = 10


CONNECT_TIMEOUT = 10
READ_TIMEOUT = 20
MAX_REDIRECTS = 10

RETRY_COUNT = 1
RETRY_BACKOFF = [1, 2]
RETRY_STATUSES = {502, 503, 504}
NO_RETRY_STATUSES = {404, 410, 401, 403}

MAX_XML_GZ_SIZE = 50 * 1024 * 1024
MAX_HTML_PARSE_SIZE = 512 * 1024

THIN_CONTENT_THRESHOLD = 100
VERY_THIN_CONTENT_THRESHOLD = 50
LONG_TITLE_THRESHOLD = 60
SHORT_TITLE_THRESHOLD = 10
LONG_META_DESC_THRESHOLD = 160

USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

ALLOWED_SCHEMES = {"http", "https"}
REJECTED_SCHEMES = {"javascript", "mailto", "data", "ftp", "file"}

TURSO_URL = os.environ.get("TURSO_DATABASE_URL", "libsql://sitemapdb-smlcodes.aws-ap-south-1.turso.io")
TURSO_TOKEN = os.environ.get("TURSO_AUTH_TOKEN", "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODcyOTUxNjEsImlkIjoiMDFhMDIxZTMtYWQwMS03OGU4LWFhMjUtN2QzNDViMDRlNTIwIiwia2lkIjoiaHEwWWo5NVdoeUoxSFFnd196bjlUZTJCVU1VbHY1WG9QbGRYRlVKR2VjZyIsInJpZCI6ImRkOTg0ZDJmLTk0MDktNDgyYy1hZmIxLTdkNzMzZDE1NDE4MSJ9.INjvr81jxLNLZYNROB5aXN2r5jIKtWqO5PUKtAc4d3SWAVqXJBfJdQCMzyRIXKCBXSWNIopdEPhKU9mOK4AyAw")

